service: crud-serverless-users

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'dynamoDB:*'
          Resource: arn:aws:dynamodb:us-east-1:125137910162:table/usersTable

plugins:
  - serverless-offline
  - serverless-dynamodb-local

package:
  individually: true
  patterns:
    - '!.dynamodb'
    - '!node_modules/**'

custom:
  dynamodb:
    # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

functions:
  get_userid:
    handler: READ/get_userid.get_userid
    package:
      patterns: 'READ/get_userid.js'
    events:
      - http:
          path: users/{id}
          method: GET

  get_users:
    handler: READ/get_users.get_users
    package:
      patterns: 'READ/get_users.js'
    events:
      - http:
          path: users
          method: GET

  post_user:
    handler: CREATE/post_user.post_user
    package:
      patterns: 'CREATE/post_user.js'
    events:
      - http:
          path: users
          method: POST

  update_user:
    handler: UPDATE/update_user.update_user
    package:
      patterns: 'UPDATE/update_user.js'
    events:
      - http:
          path: users/{id}
          method: PATCH

  delete_user:
    handler: DELETE/delete_user.delete_user
    package:
      patterns: 'DELETE/delete_user.js'
    events:
      - http:
          path: users/{id}
          method: DELETE

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
